CarParts/CarParts.Web/Areas/Admin/Controllers/HomeController.cs
namespace CarParts.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : AdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CarParts/CarParts.Web/Areas/Admin/Controllers/RentController.cs
namespace CarParts.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Data.Interfaces;

    public class RentController : AdminController
    {
        private readonly IRentService _rentService;

        public RentController(IRentService rentService)
        {
            _rentService = rentService;
        }

        public async Task<IActionResult> All()
        {
            var rents = await _rentService.GetAllRentsAsync();
            return View(rents);
        }
    }
}

CarParts/CarParts.Web/Controllers/HomeController.cs
namespace CarParts.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services.Data.Interfaces;
    using ViewModels.Statistics;

    public class HomeController : BaseController
    {
        private readonly IStatisticsService _statisticsService;

        public HomeController(IStatisticsService statisticsService)
        {
            _statisticsService = statisticsService;
        }


        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var statistics = new StatisticsViewModel
            {
                TotalCars = await _statisticsService.GetTotalCars(),
                TotalParts = await _statisticsService.GetTotalParts(),
                TotalUsers = await _statisticsService.GetTotalUsers(),
                TotalDealers = await _statisticsService.GetTotalDealers(),
                TotalRents = await _statisticsService.GetTotalRents()
            };

            return View(statistics);
        }

        [AllowAnonymous]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            if (statusCode == 400 || statusCode == 404)
            {
                return View("Error404");
            }

            return View();
        }

        [AllowAnonymous]
        public IActionResult Contacts()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult UsefulTips()
        {
            return View();
        }
    }
}

CarParts/CarParts.Web/Controllers/UserController.cs
namespace CarParts.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Data.Interfaces;

    public class UserController : BaseController
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> AddMoney()
        {
            try
            {
                await _userService.AddMoneyAsync(GetUserId());

                TempData["SuccessMessage"] = "You added 100 euro to your balance!";
                return RedirectToAction("EditAccountSettings", "Dashboard", new { id = GetUserId() });
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        public async Task<IActionResult> ResetMoney()
        {
            try
            {
                await _userService.ResetMoneyAsync(GetUserId());

                TempData["SuccessMessage"] = "You have successfully reset your balance!";
                return RedirectToAction("EditAccountSettings", "Dashboard", new { id = GetUserId() });
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        public async Task<IActionResult> AddCustomAmountMoney(double amount)
        {
            try
            {
                await _userService.AddCustomAmountMoneyAsync(GetUserId(), amount);

                TempData["SuccessMessage"] = $"You added {amount} euro to your balance!";
                return RedirectToAction("EditAccountSettings", "Dashboard", new { id = GetUserId() });
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        private IActionResult GeneralError()
        {
            TempData["ErrorMessage"] =
                "Unexpected error occurred! Please try again later or contact administrator.";

            return RedirectToAction("Index", "Home");
        }
    }
}

CarParts/CarParts.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    var errorMessage = TempData["ErrorMessage"] as string;
    var successMessage = TempData["SuccessMessage"] as string;

    if (!string.IsNullOrEmpty(errorMessage))
    {
        <div class="alert alert-danger">@errorMessage</div>
    }

    if (!string.IsNullOrEmpty(successMessage))
    {
        <div class="alert alert-success">@successMessage</div>
    }
}

<div class="mt-4 p-5 bg-light text-center">
    <h2 class="display-4">Hello, Admin!</h2>
    <p class="lead mb-1 mt-3">
        This is your administrator area - you can <b>check</b>, <b>create</b>,
        <b>delete</b> and <b>edit</b> cars.
        <br />You can also <b>rent</b> the non-rented cars.
    </p>
    <p class="lead mt-1">
        You can also see <b>all users and dealers</b> and <b>all rents</b> in the
        system.
    </p>
    <hr class="my-4">
    <a asp-area="" asp-controller="Car" asp-action="All"
       class="btn btn-primary btn-lg">All Cars</a>
    <a asp-area="" asp-controller="Car" asp-action="Add"
       class="btn btn-primary btn-lg">Add Car</a>
    <span> | </span>
    <a asp-area="" asp-controller="Car" asp-action="MyCars"
       class="btn btn-primary btn-lg">My Cars</a>
    <span> | </span>
    <a asp-area="" asp-controller="Car" asp-action="MyFavoriteCars"
       class="btn btn-primary btn-lg">My Favorite Cars</a>

    <hr/>

    <a asp-area="Admin" asp-controller="Rent" asp-action="All"
       class="btn btn-info btn-lg">All Rentals</a>
    <a asp-area="Admin" asp-controller="User" asp-action="All"
       class="btn btn-info btn-lg">All Users</a>

    <hr />

    <a asp-area="Admin" asp-controller="User" asp-action="DeleteAllReviews" class="btn btn-warning btn-block">
        Delete all reviews
    </a>

</div>